<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdditionalProductSeeder extends Seeder
{
    /**
     * Helper to get category_id by slug (fallback to first category if missing)
     */
    private function getCategoryId(string $slug): int
    {
        $id = DB::table('categories')->where('slug', $slug)->value('category_id');
        if (!$id) {
            $id = (int) DB::table('categories')->orderBy('category_id')->value('category_id');
        }
        return (int) $id;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Map category slugs to ids for clarity
        $cat = [
            'obat-keras' => $this->getCategoryId('obat-keras'),
            'obat-bebas-terbatas' => $this->getCategoryId('obat-bebas-terbatas'),
            'obat-bebas' => $this->getCategoryId('obat-bebas'),
            'jamu-herbal' => $this->getCategoryId('jamu-herbal'),
            'kebutuhan-bayi-ibu' => $this->getCategoryId('kebutuhan-bayi-ibu'),
            'perawatan-wajah' => $this->getCategoryId('perawatan-wajah'),
            'perawatan-tubuh' => $this->getCategoryId('perawatan-tubuh'),
            'kosmetik' => $this->getCategoryId('kosmetik'),
            'suplemen-vitamin' => $this->getCategoryId('suplemen-vitamin'),
            'alat-kesehatan' => $this->getCategoryId('alat-kesehatan'),
            'perban-pertolongan-pertama' => $this->getCategoryId('perban-pertolongan-pertama'),
        ];

        $now = now();

        $products = [
            // Obat Keras
            [
                'name' => 'Ciprofloxacin 500mg',
                'slug' => 'ciprofloxacin-500mg',
                'description' => 'Antibiotik untuk infeksi bakteri tertentu. Penggunaan harus sesuai resep dokter.',
                'short_description' => 'Antibiotik quinolone',
                'price' => 32000.00,
                'discount_price' => null,
                'stock' => 150,
                'sku' => 'CIP-500-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Ciprofloxacin 500mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Kalbe Farma',
                    'dosis' => '2x sehari sesuai anjuran dokter',
                    'efek_samping' => 'Mual, pusing, gangguan pencernaan',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Amlodipine 5mg',
                'slug' => 'amlodipine-5mg',
                'description' => 'Obat untuk hipertensi dan angina. Hanya dengan resep dokter.',
                'short_description' => 'Antihipertensi CCB',
                'price' => 18000.00,
                'discount_price' => null,
                'stock' => 200,
                'sku' => 'AML-5-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Amlodipine besylate 5mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Dexa Medica',
                    'dosis' => '1x sehari atau sesuai resep',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Metformin 500mg',
                'slug' => 'metformin-500mg',
                'description' => 'Antidiabetik untuk mengontrol kadar gula darah. Dengan resep dokter.',
                'short_description' => 'Antidiabetik Biguanide',
                'price' => 22000.00,
                'discount_price' => null,
                'stock' => 180,
                'sku' => 'MET-500-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Metformin HCl 500mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Kimia Farma',
                    'dosis' => '2-3x sehari setelah makan',
                    'efek_samping' => 'Gangguan pencernaan, mual',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Simvastatin 20mg',
                'slug' => 'simvastatin-20mg',
                'description' => 'Menurunkan kolesterol LDL dan trigliserida. Perlu resep dokter.',
                'short_description' => 'Statin penurun kolesterol',
                'price' => 26000.00,
                'discount_price' => null,
                'stock' => 160,
                'sku' => 'SIM-20-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Simvastatin 20mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Sanbe Farma',
                    'dosis' => '1x sehari malam hari',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cefixime 200mg',
                'slug' => 'cefixime-200mg',
                'description' => 'Antibiotik sefalosporin generasi ketiga. Gunakan sesuai resep.',
                'short_description' => 'Antibiotik sefalosporin',
                'price' => 45000.00,
                'discount_price' => 42000.00,
                'stock' => 120,
                'sku' => 'CEF-200-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Cefixime 200mg',
                    'kemasan' => '10 kapsul per strip',
                    'produsen' => 'Meiji',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Omeprazole 20mg',
                'slug' => 'omeprazole-20mg',
                'description' => 'Mengurangi produksi asam lambung untuk GERD. Resep dokter diperlukan.',
                'short_description' => 'PPI untuk GERD',
                'price' => 24000.00,
                'discount_price' => null,
                'stock' => 140,
                'sku' => 'OME-20-001',
                'category_id' => $cat['obat-keras'],
                'requires_prescription' => true,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Omeprazole 20mg',
                    'kemasan' => '10 kapsul per strip',
                    'produsen' => 'Phapros',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Obat Bebas Terbatas
            [
                'name' => 'Asam Mefenamat 500mg',
                'slug' => 'asam-mefenamat-500mg',
                'description' => 'Pereda nyeri dan anti-inflamasi. Ikuti aturan pakai.',
                'short_description' => 'NSAID pereda nyeri',
                'price' => 16000.00,
                'discount_price' => null,
                'stock' => 220,
                'sku' => 'ASM-MEF-500-001',
                'category_id' => $cat['obat-bebas-terbatas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Mefenamic Acid 500mg',
                    'kemasan' => '10 kapsul per strip',
                    'produsen' => 'Bernofarm',
                    'dosis' => '3x sehari setelah makan',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CTM 4mg',
                'slug' => 'ctm-4mg',
                'description' => 'Antihistamin untuk alergi ringan. Dapat menyebabkan kantuk.',
                'short_description' => 'Antihistamin',
                'price' => 7000.00,
                'discount_price' => null,
                'stock' => 300,
                'sku' => 'CTM-4-001',
                'category_id' => $cat['obat-bebas-terbatas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Chlorpheniramine maleate 4mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Phapros',
                    'efek_samping' => 'Kantuk, mulut kering',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Antasida Doen Tablet',
                'slug' => 'antasida-doen-tablet',
                'description' => 'Meredakan gejala maag dan asam lambung.',
                'short_description' => 'Antasida untuk maag',
                'price' => 9000.00,
                'discount_price' => null,
                'stock' => 280,
                'sku' => 'ANT-DOEN-001',
                'category_id' => $cat['obat-bebas-terbatas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Mg(OH)2, Al(OH)3, Simethicone',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Kimia Farma',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dextromethorphan 15mg',
                'slug' => 'dextromethorphan-15mg',
                'description' => 'Obat penekan batuk kering. Ikuti dosis anjuran.',
                'short_description' => 'Antitusif',
                'price' => 12000.00,
                'discount_price' => null,
                'stock' => 240,
                'sku' => 'DEX-15-001',
                'category_id' => $cat['obat-bebas-terbatas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Dextromethorphan HBr 15mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Indofarma',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Guaifenesin 100mg',
                'slug' => 'guaifenesin-100mg',
                'description' => 'Ekspektoran untuk membantu mengeluarkan dahak.',
                'short_description' => 'Ekspektoran',
                'price' => 11000.00,
                'discount_price' => null,
                'stock' => 260,
                'sku' => 'GUA-100-001',
                'category_id' => $cat['obat-bebas-terbatas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Guaifenesin 100mg',
                    'kemasan' => '10 tablet per strip',
                    'produsen' => 'Holi Pharma',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Obat Bebas
            [
                'name' => 'Promag Tablet',
                'slug' => 'promag-tablet',
                'description' => 'Meredakan nyeri lambung dan gejala maag.',
                'short_description' => 'Antasida tablet',
                'price' => 14000.00,
                'discount_price' => null,
                'stock' => 300,
                'sku' => 'PRO-MAG-001',
                'category_id' => $cat['obat-bebas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'box',
                'specifications' => json_encode([
                    'komposisi' => 'Mg(OH)2, Al(OH)3, Simethicone',
                    'kemasan' => '1 box isi 12 tablet',
                    'produsen' => 'Kalbe',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'OBH Combi Batuk',
                'slug' => 'obh-combi-batuk',
                'description' => 'Sirup batuk dengan kombinasi ekspektoran dan antitusif.',
                'short_description' => 'Sirup batuk',
                'price' => 18000.00,
                'discount_price' => null,
                'stock' => 250,
                'sku' => 'OBH-COM-001',
                'category_id' => $cat['obat-bebas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Guaifenesin, Dextromethorphan, Paracetamol',
                    'kemasan' => '100ml per botol',
                    'produsen' => 'Combiphar',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Antimo',
                'slug' => 'antimo',
                'description' => 'Membantu mencegah mabuk perjalanan.',
                'short_description' => 'Antimabuk',
                'price' => 7000.00,
                'discount_price' => null,
                'stock' => 320,
                'sku' => 'ANT-IMO-001',
                'category_id' => $cat['obat-bebas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'strip',
                'specifications' => json_encode([
                    'komposisi' => 'Dimenhydrinate 50mg',
                    'kemasan' => '4 tablet per strip',
                    'produsen' => 'Tempo Scan',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Minyak Kayu Putih 60ml',
                'slug' => 'minyak-kayu-putih-60ml',
                'description' => 'Menghangatkan tubuh dan meredakan pegal.',
                'short_description' => 'Minyak kayu putih',
                'price' => 16000.00,
                'discount_price' => null,
                'stock' => 400,
                'sku' => 'MKP-60-001',
                'category_id' => $cat['obat-bebas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Oleum cajuputi',
                    'kemasan' => '60ml per botol',
                    'produsen' => 'Cap Lang',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Salonpas Patch',
                'slug' => 'salonpas-patch',
                'description' => 'Plester pereda nyeri otot dan sendi.',
                'short_description' => 'Plester pereda nyeri',
                'price' => 12000.00,
                'discount_price' => null,
                'stock' => 280,
                'sku' => 'SAL-PAT-001',
                'category_id' => $cat['obat-bebas'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'box',
                'specifications' => json_encode([
                    'komposisi' => 'Methyl Salicylate, Menthol, Camphor',
                    'kemasan' => '1 box isi 10 plester',
                    'produsen' => 'Hisamitsu',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Jamu & Herbal
            [
                'name' => 'Temulawak Sachet',
                'slug' => 'temulawak-sachet',
                'description' => 'Jamu tradisional untuk kesehatan pencernaan dan hati.',
                'short_description' => 'Jamu temulawak',
                'price' => 4000.00,
                'discount_price' => null,
                'stock' => 350,
                'sku' => 'JAM-TEM-001',
                'category_id' => $cat['jamu-herbal'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'sachet',
                'specifications' => json_encode([
                    'komposisi' => 'Ekstrak Curcuma xanthorrhiza',
                    'kemasan' => '1 sachet 20g',
                    'produsen' => 'Jamu IBOE',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sari Kurma Botol',
                'slug' => 'sari-kurma-botol',
                'description' => 'Suplemen herbal dari ekstrak kurma untuk stamina.',
                'short_description' => 'Sari kurma',
                'price' => 28000.00,
                'discount_price' => null,
                'stock' => 200,
                'sku' => 'SAR-KUR-001',
                'category_id' => $cat['jamu-herbal'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Ekstrak buah kurma',
                    'kemasan' => '350ml per botol',
                    'produsen' => 'Al-Jazira',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Kapsul Kunyit',
                'slug' => 'kapsul-kunyit',
                'description' => 'Herbal antiinflamasi dari ekstrak kunyit.',
                'short_description' => 'Herbal kunyit kapsul',
                'price' => 25000.00,
                'discount_price' => null,
                'stock' => 180,
                'sku' => 'KAP-KUN-001',
                'category_id' => $cat['jamu-herbal'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Curcuma longa extract',
                    'kemasan' => '50 kapsul per botol',
                    'produsen' => 'Herbana',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Kebutuhan Bayi & Ibu
            [
                'name' => 'Diapers Size M',
                'slug' => 'diapers-size-m',
                'description' => 'Popok sekali pakai untuk bayi ukuran M.',
                'short_description' => 'Popok bayi M',
                'price' => 85000.00,
                'discount_price' => 80000.00,
                'stock' => 120,
                'sku' => 'DIP-M-001',
                'category_id' => $cat['kebutuhan-bayi-ibu'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'box',
                'specifications' => json_encode([
                    'komposisi' => 'SAP, Non-woven fabric',
                    'kemasan' => '1 box isi 34 pcs',
                    'produsen' => 'MamyPoko',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Baby Wipes Unscented',
                'slug' => 'baby-wipes-unscented',
                'description' => 'Tisu basah bayi tanpa pewangi untuk kulit sensitif.',
                'short_description' => 'Tisu basah bayi',
                'price' => 18000.00,
                'discount_price' => null,
                'stock' => 200,
                'sku' => 'BWB-UNS-001',
                'category_id' => $cat['kebutuhan-bayi-ibu'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pack',
                'specifications' => json_encode([
                    'komposisi' => 'Purified water, Aloe extract',
                    'kemasan' => '1 pack isi 80 lembar',
                    'produsen' => 'Pigeon',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Minyak Telon 60ml',
                'slug' => 'minyak-telon-60ml',
                'description' => 'Minyak untuk menghangatkan tubuh bayi.',
                'short_description' => 'Minyak telon bayi',
                'price' => 17000.00,
                'discount_price' => null,
                'stock' => 220,
                'sku' => 'TEL-60-001',
                'category_id' => $cat['kebutuhan-bayi-ibu'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Coconut oil, Cajuput oil, Anise oil',
                    'kemasan' => '60ml per botol',
                    'produsen' => 'My Baby',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Perawatan Wajah
            [
                'name' => 'Facial Wash Gentle',
                'slug' => 'facial-wash-gentle',
                'description' => 'Pembersih wajah lembut untuk kulit normal-sensitif.',
                'short_description' => 'Pembersih wajah',
                'price' => 35000.00,
                'discount_price' => null,
                'stock' => 180,
                'sku' => 'FAC-WAS-001',
                'category_id' => $cat['perawatan-wajah'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'tube',
                'specifications' => json_encode([
                    'komposisi' => 'Glycerin, Mild surfactants',
                    'kemasan' => '100ml per tube',
                    'produsen' => 'Wardah',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sunscreen SPF 50',
                'slug' => 'sunscreen-spf-50',
                'description' => 'Tabir surya SPF 50 untuk perlindungan kulit dari UV.',
                'short_description' => 'Tabir surya SPF50',
                'price' => 75000.00,
                'discount_price' => 70000.00,
                'stock' => 160,
                'sku' => 'SUN-SPF50-001',
                'category_id' => $cat['perawatan-wajah'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'tube',
                'specifications' => json_encode([
                    'komposisi' => 'Chemical UV filters, Vitamin E',
                    'kemasan' => '50ml per tube',
                    'produsen' => 'Skin Aqua',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Perawatan Tubuh
            [
                'name' => 'Hand Sanitizer 500ml',
                'slug' => 'hand-sanitizer-500ml',
                'description' => 'Pembersih tangan berbasis alkohol untuk perlindungan cepat.',
                'short_description' => 'Pembersih tangan',
                'price' => 30000.00,
                'discount_price' => null,
                'stock' => 220,
                'sku' => 'HAN-SAN-500-001',
                'category_id' => $cat['perawatan-tubuh'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Alcohol 70%, Glycerin, Aqua',
                    'kemasan' => '500ml per botol',
                    'produsen' => 'Antis',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Body Lotion Moisture',
                'slug' => 'body-lotion-moisture',
                'description' => 'Lotion pelembap untuk kulit kering.',
                'short_description' => 'Lotion pelembap',
                'price' => 42000.00,
                'discount_price' => null,
                'stock' => 190,
                'sku' => 'BOD-LOT-001',
                'category_id' => $cat['perawatan-tubuh'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Shea butter, Vitamin E',
                    'kemasan' => '200ml per botol',
                    'produsen' => 'Nivea',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Kosmetik
            [
                'name' => 'Lip Balm Moist',
                'slug' => 'lip-balm-moist',
                'description' => 'Pelembap bibir dengan vitamin E.',
                'short_description' => 'Pelembap bibir',
                'price' => 18000.00,
                'discount_price' => null,
                'stock' => 260,
                'sku' => 'LIP-BAL-001',
                'category_id' => $cat['kosmetik'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pcs',
                'specifications' => json_encode([
                    'komposisi' => 'Beeswax, Shea butter, Vitamin E',
                    'kemasan' => '1 pcs',
                    'produsen' => 'Maybelline',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Compact Powder Natural',
                'slug' => 'compact-powder-natural',
                'description' => 'Bedak padat untuk tampilan natural.',
                'short_description' => 'Bedak padat',
                'price' => 38000.00,
                'discount_price' => null,
                'stock' => 170,
                'sku' => 'COM-PWD-001',
                'category_id' => $cat['kosmetik'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pcs',
                'specifications' => json_encode([
                    'komposisi' => 'Talc, Mica, Titanium dioxide',
                    'kemasan' => '1 pcs',
                    'produsen' => 'Wardah',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Suplemen & Vitamin
            [
                'name' => 'Vitamin D3 1000 IU',
                'slug' => 'vitamin-d3-1000-iu',
                'description' => 'Suplemen vitamin D3 untuk kesehatan tulang dan imun.',
                'short_description' => 'Vitamin D3',
                'price' => 65000.00,
                'discount_price' => 60000.00,
                'stock' => 200,
                'sku' => 'VIT-D3-1000-001',
                'category_id' => $cat['suplemen-vitamin'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Cholecalciferol 1000 IU',
                    'kemasan' => '30 kapsul per botol',
                    'produsen' => 'Blackmores',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Zinc 20mg',
                'slug' => 'zinc-20mg',
                'description' => 'Suplemen zinc untuk dukungan imun dan kulit.',
                'short_description' => 'Mineral zinc',
                'price' => 28000.00,
                'discount_price' => null,
                'stock' => 220,
                'sku' => 'ZIN-20-001',
                'category_id' => $cat['suplemen-vitamin'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Zinc sulfate 20mg',
                    'kemasan' => '50 tablet per botol',
                    'produsen' => 'Nature Plus',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Omega-3 Fish Oil',
                'slug' => 'omega-3-fish-oil',
                'description' => 'Minyak ikan kaya EPA & DHA untuk kesehatan jantung.',
                'short_description' => 'Minyak ikan',
                'price' => 95000.00,
                'discount_price' => 90000.00,
                'stock' => 150,
                'sku' => 'OMG-FIS-001',
                'category_id' => $cat['suplemen-vitamin'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Fish oil with EPA & DHA',
                    'kemasan' => '60 kapsul per botol',
                    'produsen' => 'Nordic Naturals',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Probiotik',
                'slug' => 'probiotik',
                'description' => 'Suplemen probiotik untuk kesehatan pencernaan.',
                'short_description' => 'Probiotik',
                'price' => 48000.00,
                'discount_price' => null,
                'stock' => 160,
                'sku' => 'PRO-BIO-001',
                'category_id' => $cat['suplemen-vitamin'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Lactobacillus & Bifidobacterium strains',
                    'kemasan' => '30 kapsul per botol',
                    'produsen' => 'GNC',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Alat Kesehatan
            [
                'name' => 'Pulse Oximeter',
                'slug' => 'pulse-oximeter',
                'description' => 'Alat ukur saturasi oksigen dan nadi.',
                'short_description' => 'Oximeter',
                'price' => 150000.00,
                'discount_price' => 140000.00,
                'stock' => 90,
                'sku' => 'PUL-OXI-001',
                'category_id' => $cat['alat-kesehatan'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pcs',
                'specifications' => json_encode([
                    'fitur' => 'OLED display, auto-off',
                    'kemasan' => 'Unit + baterai + manual',
                    'produsen' => 'Onemed',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Glucometer Test Strips',
                'slug' => 'glucometer-test-strips',
                'description' => 'Strip uji gula darah untuk glucometer.',
                'short_description' => 'Strip gula darah',
                'price' => 120000.00,
                'discount_price' => null,
                'stock' => 110,
                'sku' => 'GLU-STR-001',
                'category_id' => $cat['alat-kesehatan'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'box',
                'specifications' => json_encode([
                    'komposisi' => 'Enzim glukosa oksidase',
                    'kemasan' => '50 strips per box',
                    'produsen' => 'Accu-Chek',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Nebulizer Portable',
                'slug' => 'nebulizer-portable',
                'description' => 'Alat terapi uap untuk gangguan pernapasan.',
                'short_description' => 'Nebulizer',
                'price' => 350000.00,
                'discount_price' => 330000.00,
                'stock' => 60,
                'sku' => 'NEB-POR-001',
                'category_id' => $cat['alat-kesehatan'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pcs',
                'specifications' => json_encode([
                    'fitur' => 'Portable, USB charge',
                    'kemasan' => 'Unit + masker + manual',
                    'produsen' => 'Omron',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Perban & Pertolongan Pertama
            [
                'name' => 'Kasa Steril 10x10cm',
                'slug' => 'kasa-steril-10x10cm',
                'description' => 'Kasa steril untuk perawatan luka.',
                'short_description' => 'Kasa steril',
                'price' => 15000.00,
                'discount_price' => null,
                'stock' => 240,
                'sku' => 'KAS-STE-10-001',
                'category_id' => $cat['perban-pertolongan-pertama'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'pack',
                'specifications' => json_encode([
                    'komposisi' => 'Cotton sterile gauze',
                    'kemasan' => 'Isi 10 lembar 10x10cm',
                    'produsen' => 'Onemed',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Antiseptic Spray 100ml',
                'slug' => 'antiseptic-spray-100ml',
                'description' => 'Semprot antiseptik untuk membersihkan luka dan permukaan.',
                'short_description' => 'Spray antiseptik',
                'price' => 22000.00,
                'discount_price' => null,
                'stock' => 200,
                'sku' => 'ANT-SPR-100-001',
                'category_id' => $cat['perban-pertolongan-pertama'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'botol',
                'specifications' => json_encode([
                    'komposisi' => 'Chlorhexidine, Alcohol',
                    'kemasan' => '100ml per botol',
                    'produsen' => 'Betadine',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Plester Kasa Roll',
                'slug' => 'plester-kasa-roll',
                'description' => 'Plester kasa gulung untuk balutan luka.',
                'short_description' => 'Plester roll',
                'price' => 18000.00,
                'discount_price' => null,
                'stock' => 210,
                'sku' => 'PLE-KAS-ROL-001',
                'category_id' => $cat['perban-pertolongan-pertama'],
                'requires_prescription' => false,
                'is_active' => true,
                'unit' => 'roll',
                'specifications' => json_encode([
                    'komposisi' => 'Cotton adhesive gauze',
                    'kemasan' => '1 roll 5m',
                    'produsen' => 'Hansaplast',
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Normalize fields to match current schema constraints
        $allowedUnits = ['pcs', 'box', 'botol', 'strip', 'tube', 'sachet'];
        $unitMap = [
            'pack' => 'box',
            'roll' => 'pcs',
        ];

        foreach ($products as &$product) {
            if (isset($product['unit'])) {
                $unit = $product['unit'];
                if (!in_array($unit, $allowedUnits, true)) {
                    $product['unit'] = $unitMap[$unit] ?? 'pcs';
                }
            }
        }
        unset($product);

        // Insert/update products using slug as unique key to avoid conflicts
        foreach ($products as $product) {
            DB::table('products')->updateOrInsert(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}